language: node_js
node_js:
- '10'
- '12'
before_install:
  - npm install -g npm
  - npm install -g greenkeeper-lockfile
install: npm install
before_script:
- npm install
- greenkeeper-lockfile-update
script:
- make eslint
- make test
after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: n7DQ4wpQuKap/bbQVgl5yJRFHWv/8i2mTqMTg4UaRp+VhxevLzR+PSpfzdQipopRDQXNzQu/1K+BcvOFSfQHsiS1t/kork26DNM9VmI6iU9fd89+jl2536W6VaBobXCOY7FiugniuEiYUyZOJLCF98+5nZ/RyBcR83VRAEIePKabKq2dFy9x+Nel6GjJi8yaNo/RqDL4xyue4s4BbrVerbyMRQP3D7UWQKjLEdmB4qS4auL9iTDrvNPgYTCXDhpMD0fUsIb8O4yaMTfVeiZ6xdxLjX3QDPv60U8Jt7IkElLNLH3NpJ9uuK7zDPdVDQPcSiqG4ufoVrFqauLKBScP+WtgzADnGxZLTLtBWQVYnVE+Hdqm/dpkPIQtfYvbepZZELRc9o4WrUx0wcvE2/61rb7b+zlY08TCrsuxnBNfW27BKE31YCCc0bwL9C86/TO28wIwpRRN4M9Fa14LimdaDoppkT41NL3xoetAuFG9XgkkE1pNILNMJ5FqtYwEXYNrNqmUS7eRZOPAJKgGdFPcus8lhtfxnUuspOUB1LkLDZZHkn2sIBCqjbp67fsOG7WC2avrzKvedok75waDOpfxpKCktuw7vt9RHxTME0TdN82Jgcjq34VPXSYpJhznlYJffq7K2l+LQ98moYoMnOwX2xbi4zQ8Xs/FxNF214D17XA=
